README.md, examples/disbursement.js, src/card/card.d.ts, src/card/refund.d.ts, src/card/refund.js, src/disbursement/bank.d.ts, src/disbursement/bank.js, src/disbursement/disburse.d.ts, src/disbursement/disburse.js, src/disbursement/disbursement.d.ts, src/disbursement/disbursement.js, src/disbursement/index.js, src/utils/auth.d.ts, src/utils/auth.js, src/utils/validate.d.ts, src/utils/validate.js, src/va/va.d.ts, src/xendit.d.ts, src/xendit.js, src/xendit_opts.d.ts, test/disbursement/bank.test.js, test/disbursement/constants.js, test/disbursement/disburse.test.js, test/disbursement/disbursement.test.js
- **note**: document all methods' signatures
=> Disbursement Service

.npmignore, package-lock.json, package.json
I have published latest version 0.1.2 from this branch as well (not recommended though, let's make sure latest version is always published from `master` after this experiment)
=> Using `np` as package publication management tool 

examples/invoice.js, examples/xendit.js, src/invoice/index.js, src/invoice/invoice.d.ts, src/invoice/invoice.js, src/utils/index.js, src/utils/query_string_with_no_undefined.d.ts, src/utils/query_string_with_no_undefined.js, src/xendit.d.ts, src/xendit.js, test/invoice/constants.js, test/invoice/invoice.test.js
To be release in the next minor
=> Invoice Service

.eslintrc, .github/workflows/lint.yml, package-lock.json, package.json, src/utils/fetch_with_http_err.d.ts, src/utils/prom_with_js_err.d.ts
Resolves #17 
- Add ts to linting process:
- manually linting commands in [package.json](./package.json)
- auto linting pre-commit
- Add custom config for ts in [.eslintrc](./eslintrc)
- Add linting to github workflows
=> TS linting

README.md, examples/recurring.js, integration_test/index.js, integration_test/recurring.test.js, src/recurring/index.js, src/recurring/manage_payments.d.ts, src/recurring/manage_payments.js, src/recurring/operate_payments.d.ts, src/recurring/operate_payments.js, src/recurring/recurring.d.ts, src/recurring/recurring.js, src/utils/validate.js, src/xendit.d.ts, src/xendit.js, test/recurring/constants.js, test/recurring/manage_payments.test.js, test/recurring/operate_payments.test.js, test/recurring/recurring.test.js, test/utils/validate.test.js, test/va/account.test.js
- create payment
- get payment
- edit payment
- stop payment
- pause payment
- resume payment
=> Recurring payments endpoints

README.md, examples/payout.js, integration_test/index.js, integration_test/payout.test.js, src/payout/index.js, src/payout/payout.d.ts, src/payout/payout.js, src/xendit.d.ts, src/xendit.js, test/payout/constants.js, test/payout/payout.test.js
- create payout
- get payout
- void payout
=> Payouts endpoints

CHANGELOG.md, README.md, examples/balance.js, integration_test/balance.test.js, integration_test/index.js, src/balance/balance.d.ts, src/balance/balance.js, src/balance/index.js, src/xendit.d.ts, src/xendit.js, test/balance/balance.test.js, test/balance/constants.js
=> Balance endpoint

src/utils/fetch_with_http_err.d.ts, src/utils/fetch_with_http_err.js
=> Inject headers for tracking purpose

README.md
=> Touch up README.md

index.d.ts, package.json
=> chore(definition): add root definition file

CHANGELOG.md, LICENSE, README.md
- Resolves #37 
- Resolves #38
=> LICENSE & miscellaneous docs updates

.github/workflows/coverage.yml, .github/workflows/lint.yml, .github/workflows/test.yml, .gitignore, README.md, package-lock.json, package.json
=> Project Health Badges

examples/with_async/ewallet.js, examples/with_promises/ewallet.js, integration_test/ewallet.test.js, integration_test/index.js, src/ewallet/ewallet.d.ts, src/ewallet/ewallet.js
=> feat(ewallet): Add X-API-VERSION header for ewallet create payment

.github/workflows/coverage.yml, README.md, examples/with_async/payout.js, examples/with_async/qr_code.js, examples/with_promises/payout.js, examples/with_promises/qr_code.js, integration_test/balance.test.js, integration_test/card.test.js, integration_test/disbursement.test.js, integration_test/ewallet.test.js, integration_test/index.js, integration_test/invoice.test.js, integration_test/payout.test.js, integration_test/qr_code.test.js, integration_test/recurring.test.js, integration_test/retail_outlet.test.js, integration_test/va.test.js, src/payout/payout.d.ts, src/payout/payout.js, src/qr_code/index.js, src/qr_code/qr_code.d.ts, src/qr_code/qr_code.js, src/xendit.d.ts, src/xendit.js, test/payout/constants.js, test/payout/payout.test.js, test/qr_code/constants.js, test/qr_code/qr_code.test.js
Resolves #53 as part of this new feature implementation
=> Add QR Code features

README.md, package.json, src/recurring/manage_payments.d.ts, src/recurring/manage_payments.js
=> Add Optional Currency Field

examples/with_async/qr_code.js, examples/with_promises/qr_code.js, integration_test/qr_code.test.js, integration_test/va.test.js, src/qr_code/qr_code.d.ts, src/qr_code/qr_code.js, test/qr_code/qr_code.test.js
- GET payments by QR code external ID
=> QR Code Endpoint

README.md
Update README.md for new library
=> README.md for QR Code Endpoint

README.md, examples/with_async/customer.js, examples/with_async/direct_debit.js, examples/with_promises/customer.js, examples/with_promises/direct_debit.js, integration_test/customer.test.js, integration_test/direct_debit.test.js, integration_test/index.js, src/customer/customer.d.ts, src/customer/customer.js, src/customer/index.js, src/direct_debit/direct_debit.d.ts, src/direct_debit/direct_debit.js, src/direct_debit/direct_debit_payment.d.ts, src/direct_debit/direct_debit_payment.js, src/direct_debit/index.js, src/direct_debit/linked_account.d.ts, src/direct_debit/linked_account.js, src/direct_debit/payment_method.d.ts, src/direct_debit/payment_method.js, src/xendit.js, test/customer/constants.js, test/customer/customer.test.js, test/direct_debit/constants.js, test/direct_debit/direct_debit.test.js, test/direct_debit/direct_debit_payment.test.js, test/direct_debit/linked_account.test.js, test/direct_debit/payment_method.test.js
**Customer**
- POST Create Customer
- GET Customer
- GET Customer by Reference ID
- PATCH Update customer
**Linked Account**
- POST Initialize Linked Account Tokenization
- POST Validate OTP for Linked Account Token
- GET Accessible Accounts by Linked Account Token
**Payment Method**
- POST Create Payment Method
- GET Payment Methods by Customer ID
**Direct Debit**
- POST Create Direct Debit Payment
- POST Validate OTP for Direct Debit Payment
- GET Direct Debit Payment Status by ID
- GET Direct Debit Payment Status by Reference ID
=> Direct Debit API

README.md, examples/with_async/ewallet.js, examples/with_promises/ewallet.js, integration_test/ewallet.test.js, src/ewallet/ewallet.d.ts, src/ewallet/ewallet.js, test/ewallet/constants.js, test/ewallet/ewallet.test.js
- `POST` Create eWallet charge
https://developers.xendit.co/api-reference/#create-ewallet-charge
- `GET` Get eWallet charge status
https://developers.xendit.co/api-reference/#get-ewallet-charge-status
-------------------------------------
P.S. Invoice server is currently down. It causes the failing integration test.
=> New eWallets API

README.md
https://github.com/xendit/xendit-node/issues/81
=> Update public docs and API Reference links

README.md, examples/with_async/ewallet.js, examples/with_promises/ewallet.js, integration_test/ewallet.test.js, src/ewallet/ewallet.d.ts, src/ewallet/ewallet.js, test/ewallet/constants.js, test/ewallet/ewallet.test.js
- support POST ewallets/charges/{id}/void
=> feat: add ewallets void endpoint

src/balance/index.d.ts, src/card/index.d.ts, src/customer/index.d.ts, src/direct_debit/index.d.ts, src/disbursement/index.d.ts, src/errors/index.d.ts, src/ewallet/index.d.ts, src/invoice/index.d.ts, src/payout/index.d.ts, src/platform/index.d.ts, src/qr_code/index.d.ts, src/recurring/index.d.ts, src/retail_outlet/index.d.ts, src/va/index.d.ts, src/xendit.d.ts
=> [API-2612] Fix: typescript declaration for services' classes not detected

README.md, src/card/charge.d.ts, src/card/charge.js
As above. Adds `for-user-id` support to get card charge.
=> chore(card): add for-user-id support to get charge

README.md, package-lock.json, package.json, src/ewallet/ewallet.d.ts, src/ewallet/ewallet.js
=> feat(ewallet): make channelProps object wallet-agnostic

src/recurring/manage_payments.d.ts, src/recurring/manage_payments.js
I need the rescheduleAt parameter in rucurring edit payment.
=> add reschduleAt parameter

src/balance/balance.js
Add for-user-id for GET Balance
=> Feat: Add for user id for balance

examples/with_async/qr_code.js, examples/with_promises/qr_code.js, integration_test/qr_code.test.js, src/qr_code/qr_code.d.ts, src/qr_code/qr_code.js, test/qr_code/constants.js
I have added metadata object to xendit-node in qr_code
=> Adding qr_code metadata

examples/with_async/card.js, examples/with_async/invoice.js, integration_test/va.test.js, package-lock.json, package.json, src/invoice/invoice.d.ts, src/invoice/invoice.js
added new params to Invoice
reminderTimeUnit: <string>,
remiderTime: <int>,
locale: <string>,
shouldAuthenticateCreditCard:<boolean>
=> invoice-paramsUpdate

README.md, examples/with_async/disbursement.js, integration_test/ewallet.test.js, package.json, src/disbursement/disburse.js
https://github.com/xendit/xendit-node/issues/140
https://github.com/xendit/xendit-node/issues/139
=> add forUserId on disbrusement

README.md, package.json, src/card/charge.d.ts, src/card/charge.js
Jira ticket : https://xendit.atlassian.net/browse/CC-7060
[Context]
- Merchant want to perform multiple charges with subscription flow [here](https://xendit.slack.com/archives/CGY42DC3T/p1661486701408169)
- Based on our documentation [here](https://docs.xendit.co/credit-cards/integrations/multiple-charges), merchant need to include `is_recurring: true` in their charge request
- Meanwhile in our SDK, we don't accomodate `is_recurring` field, so we add new field `isRecurring` to provide `is_recurring` value in charge request
Test results :
<details>
<summary>
Create multiple use token via `https://js.xendit.co/test_tokenize.html`
</summary>
```
{
"id": "63142dfa6cfcc9001a9ef74d",
"masked_card_number": "400000XXXXXX0002",
"status": "VERIFIED",
"card_info": {
"bank": "PT BANK RAKYAT INDONESIA …
```
=> Add isRecurring field in method card.createCharge

.github/workflows/api-key-scanner.yml
Add xendit api key scanner workflow to detect Api Key in PR. 
Reference :  [xendit-api-key-scanner-action](https://github.com/xendit/xendit-api-key-scanner-action)
=> chore: add xendit api key scanner workflow
